# Generated by Django 4.1 on 2023-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackr', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
