# Generated by Django 4.1 on 2023-03-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackr', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
